<%@ Page Title="" Language="C#" MasterPageFile="~/maestras/Maform.Master" AutoEventWireup="true" CodeBehind="rPersonasWf.aspx.cs" Inherits="AplicadaII.tarea4.rPersonasWf" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cuerpo" runat="server" >

    <div class="row">
        <form class="form-horizontal" id="form1" runat="server">
        <div class="col-sm-5 col-md-5 col-lg-5 col-xs-12" ; font-family: 'Bell Gothic Std Black'; font-size: larger; font-style: normal; color: #FFFFFF; text-transform: capitalize; font-variant: small-caps; font-weight: bold; visibility: inherit; table-layout: fixed; line-height: normal;">
         <div class="col-md-offset-5">
         <center><h2><label>Registrarse</label></h2></center>  </div>
        </div>
    
      
        <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
            <br>
        <br>
        <br >

            
    
  <div class="form-group">
    <label for="txtNombre" class="col-sm-2 control-label">Nombre</label>

    <div class="col-sm-6">
        <asp:TextBox ID="txtNombre" CssClass="form-control" runat="server" />
    </div>
  </div>
  
<div class="form-group">
    <label for="cbSexo" class="col-sm-2 control-label">Sexo</label>
    <div class="col-sm-5">
  <asp:DropDownList ID="cbSexo" CssClass="form-control" runat="server">
      <asp:ListItem Selected="True" Value="-1">seleccione el sexo</asp:ListItem>
      <asp:ListItem Value="M">Masculino</asp:ListItem>
      <asp:ListItem Value="F">Femenino</asp:ListItem>
   </asp:DropDownList>
    
    </div>
  </div>




   <div class="form-group">
    <label for="telefonos" class="col-sm-2 control-label">Telefonos</label>
    <div class="col-sm-6">
        <div class="well">
           <table class="table">
               <tr>
                   <td>
                       <asp:DropDownList ID="tipoTel" CssClass="form-control" runat="server">
                          <asp:ListItem Selected="True" Value="-1">Tipo de Telefono</asp:ListItem>
                          <asp:ListItem Value="Celular">Celular</asp:ListItem>
                          <asp:ListItem Value="Casa">Casa</asp:ListItem>
                           <asp:ListItem Value="Trabajo">Trabajo</asp:ListItem>
                       </asp:DropDownList>
                   </td>
                   <td>
                       <asp:TextBox runat="server" 
                   ID="txtTelefono" CssClass="form-control" ToolTip="escribe telefono"></asp:TextBox> </td>

               </tr>

           </table>
            
        </div>
    
    </div>
  </div>



  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <asp:Button runat="server" CssClass="btn btn-primary" Text="Guardar" ID="btnGuardar" OnClick="btnGuardar_Click" />
    </div>
  </div>
<br />
            
        </div>

            


            <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">

            </div>

            
            <div class="col-sm-2 col-md-2 col-lg-2 col-xs-12">
               
            <center><label>Buscar:</label></center>
            </div>

            <div class="col-sm-2 col-md-2 col-lg-2 col-xs-12">
            <asp:DropDownList ID="Tbusqueda" runat="server" CssClass="form-control">
                <asp:ListItem Value="id">Id</asp:ListItem>
                <asp:ListItem>Nombre</asp:ListItem>
                <asp:ListItem>Telefono</asp:ListItem>

            </asp:DropDownList>
            </div>

            
            <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
                <asp:TextBox ID="txtBuscar" runat="server" CssClass="form-control">

                </asp:TextBox>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2 col-xs-12">

            <asp:Button ID="btnBuscar" runat="server" Text="Buscar" CssClass="btn btn-success" OnClick="btnBuscar_Click" />
            </div>

            <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
                <br />
            <asp:GridView ID="gvPersona" runat="server" CssClass="table" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="gvPersona_RowCancelingEdit" OnRowDeleting="gvPersona_RowDeleting" OnRowEditing="gvPersona_RowEditing" OnRowUpdating="gvPersona_RowUpdating" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical">
                <AlternatingRowStyle BackColor="#DCDCDC" />
                <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#0000A9" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#000065" />
                </asp:GridView>
            </div>
            
</form>
        
         </div>
</asp:Content>
